# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  python:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Installing dependencies
          command: |
            python3 -m venv ~/.venv
            . ~/.venv/bin/activate
            pip install -r requirements.txt
            pip install -e .

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.venv"
      - run:
          name: Running tests
          command: |
            . ~/.venv/bin/activate
            pylint src tests
            mypy src tests
            pytest tests
workflows:
  version: 2
  python:
    jobs:
      - python
